nextcloud-db:
  image: mariadb
  container_name: nextcloud_db
  ports:
   - "33034:3306"
  volumes:
   - ./mariadb:/var/lib/mysql
  environment:
  - MYSQL_ROOT_PASSWORD=123456
  - MYSQL_DATABASE=nextcloud
  - MYSQL_USER=summer
  - MYSQL_PASSWORD=123456

nextcloud_web:
  image: wonderfall/nextcloud
  container_name: nextcloud_web
  environment:
    - UID=1000
    - GID=1000
    - UPLOAD_MAX_SIZE=10G
    - APC_SHM_SIZE=128M
    - OPCACHE_MEM_SIZE=128
    - CRON_PERIOD=15m
    - TZ=Asia/Shanghai
    - ADMIN_USER=admin
    - ADMIN_PASSWORD=123456
    - DOMAIN=0.0.0.0
    - DB_TYPE=mysql
    - DB_NAME=nextcloud
    - DB_USER=summer
    - DB_PASSWORD=123456
    - DB_HOST=nextcloud-db:3306
  volumes:
    - ./nextcloud/data:/data
    - ./nextcloud/config:/config
    - ./nextcloud/apps:/apps2
    - ./nextcloud/themes:/nextcloud/themes
  links:
    - nextcloud-db

nginx:
  image: nginx:alpine
  container_name: nginx
  restart: always
  ports:
    - "80:80"
  volumes:
     - ./wardpress:/var/www/html 
     - ./0.0.0.0.conf:/etc/nginx/conf.d/0.0.0.0.conf
  links:
    - nextcloud_web
